apiVersion: batch/v1
kind: CronJob
metadata:
  name: complaints-messages-dispatcher-cronjob
  namespace: {_NAMESPACE}
spec:
  schedule: "*/1 * * * *" # Run every minute
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: complaints-messages-dispatcher-container
              image: {_IMAGE}
              imagePullPolicy: Always
              command:
                - "/bin/sh"
                - '-c'
                - "npm run dispatch-messages -- --limit 10"
              resources:
                requests:
                  cpu: "250m"
                  memory: "512Mi"
                limits:
                  cpu: "250m"
                  memory: "512Mi"
          restartPolicy: OnFailure
