services:
  
  # Backend service
  acl-auth-gateway-backend:
    container_name: acl-auth-gateway-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency-base
    ports:
      - ${APP_FORWARD_PORT:-8080}:${APP_PORT:-8080}
    volumes:
      - .:/app
    networks:
      - acl_auth_gateway_network
    restart: on-failure
    tty: true
    stdin_open: true
    expose:
      - ${APP_PORT:-8080}
    environment:
      - NODE_OPTIONS=--max_old_space_size=3072
  
  # postgres DB service
  database:
    image: postgres:17-alpine3.20
    container_name: acl-auth-gateway-database
    restart: always
    ports:
      - ${DB_FORWARD_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DB_USER:-"postgres"}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-"admin@123"}
      - POSTGRES_DB=${DB_DATABASE:-"acl-auth-gateway-database"}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - acl_auth_gateway_network
  
  #pgAdmin
  pgadmin:
    image: 'dpage/pgadmin4:8.13.0'
    container_name: acl-auth-gateway-pgadmin
    restart: always
    ports:
      - ${PGADMIN_FORWARD_PORT:-8888}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-user@gmail.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin@123}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - acl_auth_gateway_network
  
  # RabbitMQ service
  rabbitmq:
    container_name: acl-auth-gateway-rabbitmq
    image: 'rabbitmq:4.0.3-management-alpine'
    restart: always
    ports:
      - "${RABBITMQ_FORWARD_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_FORWARD_PORT:-15672}:15672"
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-"guest"}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-"guest"}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-"/"}
    volumes:
        - rabbitmq:/var/lib/rabbitmq/
        - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - acl_auth_gateway_network

networks:
  acl_auth_gateway_network:
    name: acl_auth_gateway_shared_network
    external: true

volumes:
  pg_data: {}
  pgadmin_data: {}
  rabbitmq: {}
  rabbitmq_logs: {}

#docker network create acl_auth_gateway_shared_network